ops: Automates releases
superthread-com/localization pull request #114
Opened 2024-10-02 09:57 UTC by nszilard

2024-10-02 10:51 UTC, ben-bourdin451 approved these changes
looks good to me 

only thing that could potentially be worth adding is the fact that the release job depends on the ci to pass on `main` before running the release to prevent potentially bad merges to be released but no worries if this is too complex or annoying to setup

2024-10-02 10:51 UTC, ben-bourdin451 commented on .github/workflows/ci.yml
> +      - '**/*.json'
let's not try to optimise this in my opinion and just run it on each pr 🙂

2024-10-02 10:57 UTC, nszilard commented
> looks good to me
> 
> only thing that could potentially be worth adding is the fact that the release job depends on the ci to pass on `main` before running the release to prevent potentially bad merges to be released but no worries if this is too complex or annoying to setup

it's sort of implied, as you need a PR to push to main and the PR needs to be approved/pass CI, but i can add a "duplicate" version of the ci before running the release job if you wish

2024-10-02 15:04 UTC, ben-bourdin451 requested changes

2024-10-03 14:37 UTC, ben-bourdin451 approved these changes

2024-10-03 14:40 UTC, merged